#!/usr/bin/env node
const child_process = require('child_process');

//初始化所需数据或数据结构
let line_num = 1;
let proc_num = 1;
let command = null;
let inputs = null;

//读取命令
for (let i = 2; i < process.argv.length; i++) {
    let a = process.argv[i];
    if (a.startsWith('-')) {
        let optarg = process.argv[++i];
        switch (a) {
            case '-n':
                if (optarg < 1) { //TODO
                    console.error('invalid option argument');
                }
                line_num = parseInt(optarg);
                break;
            case '-P':
                proc_num = parseInt(optarg);
                break;
        }
    } else {
        command = a;
        while (++i) {
            if (i == process.argv.length) break;
            command += ` ${process.argv[i]}`;
        }
    }
}

//处理
let p = new Promise((resolve, reject) => {
    process.stdin.on('data', (data) => {
        inputs = data.toString('utf8').split(/\s+/);
    });
    process.stdin.on('end', () => {
        resolve(inputs);
    })
});

let arr = [];
let activeProcNum = 0;

let handler = (inputArrs) => {
    let k = 0;
    while (k < inputArrs.length) {
        let once_inputs = [];
        for (let j = k; j < k + line_num; j++) {
            let item = inputArrs[j];
            if ('' === item) break;
            once_inputs.push(item);
        }
        arr.push(once_inputs);
        k += line_num;
    }
    for (let ar of arr) {
        /*while (activeProcNum == proc_num) {
            if (activeProcNum != proc_num) break;
        }*/
        if (!ar.length) continue;
        if (proc_num == 1) {
            process.stdout.write(child_process.execSync(`${command || 'echo '} ${ar.join(' ')}`));
            continue;
        }
        let workerProcess = child_process.exec(`${command || 'echo '} ${ar.join(' ')}`, (error, stdout, stderr) => {
            process.stdout.write(stdout);
        });
        workerProcess.on('close', (code) => {
            --activeProcNum;
        });
        ++activeProcNum;
    }
};

p.then((inputArrs) => {
    handler(inputArrs);
});
